--- 
cwd: /var/www/apps/test
log_file: /var/www/apps/test/shared/log/mongrel.log
user: deploy
group: deploy
port: "8000"
environment: production
pid_file: /var/www/apps/test/shared/pids/mongrel.pid
servers: 3
